export const LOAD_SUMMARY = 'LOAD_SUMMARY';
export const LOAD_INDICATORS = 'LOAD_INDICATORS';
export const LOAD_INDICATORS_MARKET = 'LOAD_INDICATORS_MARKET';

export const INDICATORS_SETTINGS_CHANGE = 'INDICATORS_SETTINGS_CHANGE';
export const GLOBAL_SETTINGS_CHANGE = 'GLOBAL_SETTINGS_CHANGE';

export const ADD_BOOKMARK = 'ADD_BOOKMARK';
export const REMOVE_BOOKMARK = 'REMOVE_BOOKMARK';
export const LOAD_BOOKMARKS_INDICATORS = 'LOAD_BOOKMARKS_INDICATORS';
export const LOAD_BOOKMARK_MARKET_INDICATORS = 'LOAD_BOOKMARK_MARKET_INDICATORS';
