export const LOAD_SUMMARY = 'LOAD_SUMMARY';
export const LOAD_INDICATORS = 'LOAD_INDICATORS';
export const LOAD_INDICATORS_MARKET = 'LOAD_INDICATORS_MARKET';

export const INDICATORS_SETTINGS_CHANGE = 'INDICATORS_SETTINGS_CHANGE';
